/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FirstSignupRouteImport } from './routes/first-signup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WWorkspaceIdRouteRouteImport } from './routes/w.$workspaceId.route'
import { Route as WWorkspaceIdIndexRouteImport } from './routes/w.$workspaceId.index'
import { Route as WWorkspaceIdUsersRouteImport } from './routes/w.$workspaceId.users'
import { Route as WWorkspaceIdSettingsRouteImport } from './routes/w.$workspaceId.settings'
import { Route as WWorkspaceIdLabelsRouteImport } from './routes/w.$workspaceId.labels'
import { Route as WWorkspaceIdPProjectIdRouteImport } from './routes/w.$workspaceId.p.$projectId'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstSignupRoute = FirstSignupRouteImport.update({
  id: '/first-signup',
  path: '/first-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdRouteRoute = WWorkspaceIdRouteRouteImport.update({
  id: '/w/$workspaceId',
  path: '/w/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceIdIndexRoute = WWorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWorkspaceIdRouteRoute,
} as any)
const WWorkspaceIdUsersRoute = WWorkspaceIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => WWorkspaceIdRouteRoute,
} as any)
const WWorkspaceIdSettingsRoute = WWorkspaceIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WWorkspaceIdRouteRoute,
} as any)
const WWorkspaceIdLabelsRoute = WWorkspaceIdLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => WWorkspaceIdRouteRoute,
} as any)
const WWorkspaceIdPProjectIdRoute = WWorkspaceIdPProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => WWorkspaceIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/first-signup': typeof FirstSignupRoute
  '/login': typeof LoginRoute
  '/workspaces': typeof WorkspacesRoute
  '/w/$workspaceId': typeof WWorkspaceIdRouteRouteWithChildren
  '/w/$workspaceId/labels': typeof WWorkspaceIdLabelsRoute
  '/w/$workspaceId/settings': typeof WWorkspaceIdSettingsRoute
  '/w/$workspaceId/users': typeof WWorkspaceIdUsersRoute
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/p/$projectId': typeof WWorkspaceIdPProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/first-signup': typeof FirstSignupRoute
  '/login': typeof LoginRoute
  '/workspaces': typeof WorkspacesRoute
  '/w/$workspaceId/labels': typeof WWorkspaceIdLabelsRoute
  '/w/$workspaceId/settings': typeof WWorkspaceIdSettingsRoute
  '/w/$workspaceId/users': typeof WWorkspaceIdUsersRoute
  '/w/$workspaceId': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/p/$projectId': typeof WWorkspaceIdPProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/first-signup': typeof FirstSignupRoute
  '/login': typeof LoginRoute
  '/workspaces': typeof WorkspacesRoute
  '/w/$workspaceId': typeof WWorkspaceIdRouteRouteWithChildren
  '/w/$workspaceId/labels': typeof WWorkspaceIdLabelsRoute
  '/w/$workspaceId/settings': typeof WWorkspaceIdSettingsRoute
  '/w/$workspaceId/users': typeof WWorkspaceIdUsersRoute
  '/w/$workspaceId/': typeof WWorkspaceIdIndexRoute
  '/w/$workspaceId/p/$projectId': typeof WWorkspaceIdPProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/first-signup'
    | '/login'
    | '/workspaces'
    | '/w/$workspaceId'
    | '/w/$workspaceId/labels'
    | '/w/$workspaceId/settings'
    | '/w/$workspaceId/users'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/p/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/first-signup'
    | '/login'
    | '/workspaces'
    | '/w/$workspaceId/labels'
    | '/w/$workspaceId/settings'
    | '/w/$workspaceId/users'
    | '/w/$workspaceId'
    | '/w/$workspaceId/p/$projectId'
  id:
    | '__root__'
    | '/'
    | '/first-signup'
    | '/login'
    | '/workspaces'
    | '/w/$workspaceId'
    | '/w/$workspaceId/labels'
    | '/w/$workspaceId/settings'
    | '/w/$workspaceId/users'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/p/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FirstSignupRoute: typeof FirstSignupRoute
  LoginRoute: typeof LoginRoute
  WorkspacesRoute: typeof WorkspacesRoute
  WWorkspaceIdRouteRoute: typeof WWorkspaceIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-signup': {
      id: '/first-signup'
      path: '/first-signup'
      fullPath: '/first-signup'
      preLoaderRoute: typeof FirstSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId': {
      id: '/w/$workspaceId'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId'
      preLoaderRoute: typeof WWorkspaceIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspaceId/': {
      id: '/w/$workspaceId/'
      path: '/'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof WWorkspaceIdIndexRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/users': {
      id: '/w/$workspaceId/users'
      path: '/users'
      fullPath: '/w/$workspaceId/users'
      preLoaderRoute: typeof WWorkspaceIdUsersRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/settings': {
      id: '/w/$workspaceId/settings'
      path: '/settings'
      fullPath: '/w/$workspaceId/settings'
      preLoaderRoute: typeof WWorkspaceIdSettingsRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/labels': {
      id: '/w/$workspaceId/labels'
      path: '/labels'
      fullPath: '/w/$workspaceId/labels'
      preLoaderRoute: typeof WWorkspaceIdLabelsRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
    '/w/$workspaceId/p/$projectId': {
      id: '/w/$workspaceId/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/w/$workspaceId/p/$projectId'
      preLoaderRoute: typeof WWorkspaceIdPProjectIdRouteImport
      parentRoute: typeof WWorkspaceIdRouteRoute
    }
  }
}

interface WWorkspaceIdRouteRouteChildren {
  WWorkspaceIdLabelsRoute: typeof WWorkspaceIdLabelsRoute
  WWorkspaceIdSettingsRoute: typeof WWorkspaceIdSettingsRoute
  WWorkspaceIdUsersRoute: typeof WWorkspaceIdUsersRoute
  WWorkspaceIdIndexRoute: typeof WWorkspaceIdIndexRoute
  WWorkspaceIdPProjectIdRoute: typeof WWorkspaceIdPProjectIdRoute
}

const WWorkspaceIdRouteRouteChildren: WWorkspaceIdRouteRouteChildren = {
  WWorkspaceIdLabelsRoute: WWorkspaceIdLabelsRoute,
  WWorkspaceIdSettingsRoute: WWorkspaceIdSettingsRoute,
  WWorkspaceIdUsersRoute: WWorkspaceIdUsersRoute,
  WWorkspaceIdIndexRoute: WWorkspaceIdIndexRoute,
  WWorkspaceIdPProjectIdRoute: WWorkspaceIdPProjectIdRoute,
}

const WWorkspaceIdRouteRouteWithChildren =
  WWorkspaceIdRouteRoute._addFileChildren(WWorkspaceIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FirstSignupRoute: FirstSignupRoute,
  LoginRoute: LoginRoute,
  WorkspacesRoute: WorkspacesRoute,
  WWorkspaceIdRouteRoute: WWorkspaceIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
